name: Application Startup Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-startup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Set Environment Variables
      run: |
        echo "SYNC_DATABASE_URL=${{ secrets.SYNC_DATABASE_URL }}" >> .env
        echo "ASYNC_DATABASE_URL=${{ secrets.ASYNC_DATABASE_URL }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI Application
      run: |
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 10  # Wait for server to start

    - name: Test Application Startup
      run: curl -f http://localhost:8000 || exit 1

    - name: Stop FastAPI Application
      if: always()
      run: |
        pkill -f "uvicorn"
